### ISSUE TITLE
Torch Particles Not Actually Fixed, Colored Lamp Light Not Loading from Save

### ISSUE THREAD

**Issue by DarianLStephens** [DarkShadow44/CptsModdingLight#11]
They seem to be taking the color of skylight, since during the day, the flames will be bright and roughly as you'd expect (Though I feel they should be more orange as per the light). During night, they'll be blue again.
This happens in enclosed spaces, as well, so outside light isn't touching the particles.

Also, I'm not seeing any light from the colored lamps when loading a save with them already placed. Replacing them will fix it until you reload the world again.

**Comment by DarianLStephens** [comment]
On the plus side, Fancy Block Particles' torch particles do look correct, and they all respond correctly to lighting, so that's a pretty good workaround.

**Comment by DarkShadow44** [comment]
Thanks for the feedback! Saving should work in theory, but there's not much point since I'm reworking the saving part as well. I'll make sure to test this before the release though!

**Comment by DarianLStephens** [comment]
It may have something to do with them being powered by a redstone torch next to them, since other colored lights work just fine when loading.

**Comment by DarkShadow44** [comment]
Ah, that's a valuable detail - I actually never tested redstone lamps, only glowstone. Thanks!

**Comment by DarianLStephens** [comment]
Ah, I guess I could have been clearer that they were colored redstone lamps rather than just glowstone.
Sorry for that, but I'm glad it helps.

**Comment by DarkShadow44** [comment]
1.7.10 version is out of date, the rework is written from scratch, so I close this bug.
