### ISSUE TITLE
Re-Enable Entity Shading

### ISSUE THREAD

**Issue by DarianLStephens** [DarkShadow44/CptsModdingLight#12]
I don't know how complex the issue is or why it was disabled (Or even if it was intentional, or something that was broken and unfinished), but it's very noticeable and affects the look of the game quite a bit.
You can see it on anything, any creature, even your own hand.

**Comment by DarkShadow44** [comment]
Hey there, thanks for the report! Sorry I didn't reply sooner, forgot to enable notifications.
Seems like I accidentally broke something. I'll look into it, currently I'm at some major reworks, but afterwards I'll fix that.
I hope I'll have that in the next release, together with colored sunlight, colored glass affecting light and twice as big light sources!

**Comment by DarianLStephens** [comment]
It was nothing you did, that's been there since the first version I can recall of Colored Lights.
Nice to hear that you'll be looking in to it, and I'll look forward to the next version.

**Comment by DarkShadow44** [comment]
1.7.10 version is out of date, the rework is written from scratch, so I close this bug.
