### ISSUE TITLE
Low-Light Static

### ISSUE THREAD

**Issue by DarianLStephens** [DarkShadow44/CptsModdingLight#24]
You may or may not be aware of this issue, but near the edges of the extent of colored lights, you'll get differently-colored 'static' on certain blocks.
You can see an example of it here:
https://imgur.com/a/5QjmMJn

Interestingly, I just discovered that some of the static will disappear entirely if you look in the right directions, and that it varies depending on the color of light.
It looks like a strange overlay on top of the block, the properties of which are easier demonstrated by video:
https://www.youtube.com/watch?v=xha7timVIVw

**Comment by DarkShadow44** [comment]
Interesting, I wasn't aware of that, thanks! Are you using smooth lighting OFF, MINIMUM or MAX?

**Comment by DarianLStephens** [comment]
It doesn't matter, the effect is there regardless (But I do have Smooth Lighting at Max by default).
Interestingly, it's insanely stronger with no smooth lighting:
https://i.imgur.com/YKEyJ59.png
It makes me wonder if Smooth Lighting is just hiding the effect for the most part.
Oddly, there's also a second ring of green static visible to the right of the image.

Here's the same scene with minimal smooth lighting:
https://i.imgur.com/PHBF1UV.png
(I could never quite tell the difference between minimal and max)

**Comment by DarianLStephens** [comment]
This was apparently accidentally fixed a while ago, but beware of it recurring since we don't exactly what caused it (Or it was just never outright stated).
