### ISSUE TITLE
Slight Color Mixing Issues (?)

### ISSUE THREAD

**Issue by DarianLStephens** [DarkShadow44/CptsModdingLight#27]
I'm unsure if this is just how light would work in this situation, but it seems odd that I would get this spectrum from a simple purple glass roof:
![2019-12-09_04 58 11](https://user-images.githubusercontent.com/15375876/70393782-11fa4700-1a42-11ea-90ad-183ef4754141.png)
In case it helps for testing, the roof is 7x7 Purple Stained Glass, 3 blocks off the ground.

**Comment by DarkShadow44** [comment]
Yeah, that's not how it's supposed to be. Thanks for the report, I need to work on that.

**Comment by DarkShadow44** [comment]
1.7.10 version is out of date, the rework is written from scratch, so I close this bug.
