### ISSUE TITLE
Broken/Incredibly Dark Ambient Occlusion

### ISSUE THREAD

**Issue by DarianLStephens** [DarkShadow44/CptsModdingLight#28]
In the latest update (2.1.0), the world has become very well-shaded. _Too_ well-shaded, in fact:
![2019-12-09_04 49 16](https://user-images.githubusercontent.com/15375876/70393613-d494ba00-1a3f-11ea-8c78-83e6e7cdbe48.png)

**Comment by DarianLStephens** [comment]
It also helps to highlight an issue where smooth lighting isn't oriented correctly (Or, so it seems), as you'll have smooth edges in the North-East/South-West directions, but jagged along the South-East/North-West directions:
![2019-12-09_05 14 37](https://user-images.githubusercontent.com/15375876/70393855-d318c100-1a42-11ea-8fb4-15dd1536b586.png)

**Comment by DarkShadow44** [comment]
Mhh, I've reworked all the sunlight handling - could very well be because of that. I'll look into it.

**Comment by DarianLStephens** [comment]
On the very plus side, I haven't noticed that static since the last version I could run!
The only remaining thing even close to it are slight color changes at a certain distance from the original source (Even then, I'm not entirely sure it's a genuine issue or just how light works), but otherwise it's more playable than ever!

**Comment by DarkShadow44** [comment]
An unplanned bugfix, nice! :D

**Comment by DarianLStephens** [comment]
I've just noticed the diagonal ambient occlusion problem in vanilla, so it's not an issue with this mod.
![2020-01-27_17 48 36](https://user-images.githubusercontent.com/15375876/73155015-6b6f2000-412d-11ea-9636-d03ff664e17c.png)
So, that means the biggest outstanding issues I'm aware of would be extremely dark ambient occlusion, blue sunlight not being filtered entirely correctly all the way through, and black liquids when touching a block up top.
Otherwise, this is the least buggy and most feature-complete the mod has ever been!
Oh, aside from the light color configuration file. That's still a big positive to look forward to.

**Comment by DarkShadow44** [comment]
1.7.10 version is out of date, the rework is written from scratch, so I close this bug.
