### ISSUE TITLE
Old Mod Compatibility Broken

### ISSUE THREAD

**Issue by DarianLStephens** [DarkShadow44/CptsModdingLight#30]
In the past, there were a few mods which added automatic detection for Colored Lights, and would apply RGB values to their light-emitting blocks.
Prominently, there's Project Red and similar offshoots, and Chromaticraft (Though I believe the feature was removed after Colored Lights was discontinued).
This lamp actually emitted green light in the old Colored Lights mod:
![2019-12-09_06 18 31](https://user-images.githubusercontent.com/15375876/70394723-bd5bc980-1a4b-11ea-8d32-ebf004fc9681.png)
I don't know if you can really do anything about this, or entirely if you should, since you're making a lot of changes to the mod, and while I would think mods _should_ work with it, there's no guarantee they'll remain able to handle it without themselves being updated.
Chromaticraft is probably the only one which has a chance of being updated to support this mod again, though.

**Comment by DarkShadow44** [comment]
This is because I renamed the mod, they don't recognize it anymore. Once the mod is stable enough, maybe I can re-add the api to be available for other mods.
Or, as planned, I just provide a config that is preconfigured for the lights of other mods, then we wouldn't need an API at all.

**Comment by DarianLStephens** [comment]
I personally would very much prefer the config.

**Comment by DarkShadow44** [comment]
1.7.10 version is out of date, the rework is written from scratch, so I close this bug. New version will come with a config. Some day. :D
