### ISSUE TITLE
Horizon Darkening at a Certain Distance from the Ground

### ISSUE THREAD

**Issue by DarianLStephens** [DarkShadow44/CptsModdingLight#32]
If you went in to creative and flew up a short distance, you'll see that the skyline darkens.
Interestingly, the light value reported in F3 also changes at the transition point, so the screenshots will have that open.
Normal Skyline:
![2019-12-09_06 27 21](https://user-images.githubusercontent.com/15375876/70394861-2a239380-1a4d-11ea-8549-36099b5a9b30.png)
Darkened Skyline:
![2019-12-09_06 27 18](https://user-images.githubusercontent.com/15375876/70394864-360f5580-1a4d-11ea-8aa1-590ad171a080.png)

**Comment by DarianLStephens** [comment]
Given the fact that it happens after going a bit away from terrain, and the reported light value changes, I can't help but wonder if this is related to the water issue reported in issue #29.

**Comment by DarkShadow44** [comment]
Interesting, this always happens when you fly up, no matter where?

**Comment by DarianLStephens** [comment]
It seems to. It also does seem at least somewhat based on the distance you are above the terrain, as flying over a bumpy or mountainous area will result in the sky repeatedly brightening and darkening.

**Comment by DarkShadow44** [comment]
Fixed as of 2.1.2. If you still encounter this issue, please tell me.
