### ISSUE TITLE
Missing Fog

### ISSUE THREAD

**Issue by DarianLStephens** [DarkShadow44/CptsModdingLight#33]
In vanilla Minecraft, there usually exists a layer of fog along the horizon, which helps to hide chunks loading.
This seems to have been broken or deliberately disabled back in the original Colored Lights mod:
![2019-12-09_15 56 37](https://user-images.githubusercontent.com/15375876/70408552-adb8a100-1a9c-11ea-8ffd-c002bc8f9931.png)
I imagine it was planned to have fog render again at some point, but also that it wasn't a priority.

You can still see the fog in the skyline, just not on actual terrain.

**Comment by DarkShadow44** [comment]
Huh, never noticed. I'll look into it, but it's not high priority.

**Comment by DarkShadow44** [comment]
1.7.10 version is out of date, the rework is written from scratch, so I close this bug.
