### ISSUE TITLE
Enchantment Animation Broken

### ISSUE THREAD

**Issue by DarianLStephens** [DarkShadow44/CptsModdingLight#35]
Enchanted items will have some purpleness to them, but it won't move, and appears as two lines straight up and down from its original texture orientation (I,E, the lines don't change their rotation at all relative to the item's texture).
![2019-12-10_03 29 42](https://user-images.githubusercontent.com/15375876/70453713-572f7f00-1afd-11ea-9987-cde3e66662c0.png)

**Comment by DarkShadow44** [comment]
Interesting thanks, I'll look into it.

**Comment by DarkShadow44** [comment]
1.7.10 version is out of date, the rework is written from scratch, so I close this bug.
