### ISSUE TITLE
optifine compatibility

### ISSUE THREAD

**Issue by SkySem** [DarkShadow44/CptsModdingLight#37]
When you start the game, lightoverhaul-1.7.10-2.1.0 together with mod OptiFine_1.7.10_HD_U_E7, the game crashes. at the stage of entering the server - a render error

"java.lang.ClassCastException: net.minecraft.client.renderer.Tessellator cannot be cast to com.darkshadow44.lightoverhaul.interfaces.ITessellatorMixin"

**Comment by DarkShadow44** [comment]
Yeah, the mod is fundamentally incompatible with OptiFine. Sorry about that.

**Comment by SkySem** [comment]
generally ? never?

**Comment by DarkShadow44** [comment]
Probably not. OptiFine is changing the rendering system too much to be compatible.

**Comment by DarkShadow44** [comment]
1.7.10 version is out of date, the rework is written from scratch, so I close this bug.
New version will be compatible with sodium, so there's that. :)
