### ISSUE TITLE
ELN compatability, question/request

### ISSUE THREAD

**Issue by Elgh-github** [DarkShadow44/CptsModdingLight#38]
Hi! I'm currently developing my own version of ELN, with edits, new blocks, balance changes etc.
Is it known why eln's block's textures don't show up correctly? I myself, don't really know how to code,
more of just ctrl+c & edit. I was hoping i could make the different types of lights (incandescent, fluorescent, led) slightly different colors, like they are in real life. Also, i want to make the HPS (high pressure sodium) streetlamps, you know, the yellow, orange-ish ones. Is there something like
setLightColor() or something like that in the colored light mod, that i can use to set it in the lamps config? Also, you don't have to if you can't/don't want to do it, but if you know what is wrong, can you please try and fix compatibility with eln. Thank you in advance!

**Comment by Elgh-github** [comment]
Well, after looking at files from the mod, i found this in the file: CLLamp.java

![dsddsd](https://user-images.githubusercontent.com/40928874/71558164-cfcc9000-2a58-11ea-9b43-4ce8a1f9bcfe.PNG)

If i put that in the config for one of the lamps, i think it would just give me errors, since eln wouldn't know what to do with that. Maybe the build would even fail, anyway, is that the right way to add color to light.

#edit#: I quess i would need to import the required files from the mod. If you can't help me, you of course don't have to. Just asking to see if you know. No pressure :)

**Comment by DarkShadow44** [comment]
First off, what is ELN? And what does "lock's textures don't show up correctly" mean? Screenshots are always helpful.

Currently the API for setting light color is disabled, since I'm still working on it. Especially for super bright lights I'm not sure how to best handle that.
Also refer to https://github.com/DarkShadow44/CptsModdingLight/issues/30 and https://github.com/DarkShadow44/CptsModdingLight/issues/2. I'll probably add a JSON into this mod to apply colors to lamps of other mods. Then it's easy for everyone to add their own colored lights, and I could add sane defaults for all mods that have custom lamps.

**Comment by Elgh-github** [comment]
Oh sorry, ELN is Electrical age. For what the textures are like, it's just some gray-ish color. I cannot provide a screenshot today, but if you need it, i'll get you one tomorrow. 
You can find the problem in the original mod compatability list. Lock's is a typo, it was meant to say block's. Again, sorry for the unclear and kinda bad post. I can wait for the JSON method of adding color. It's easier for everyone.

**Comment by Elgh-github** [comment]
![2019-12-30_12 10 06](https://user-images.githubusercontent.com/40928874/71577632-9b5edf80-2afd-11ea-9f51-6e388e3585af.png)

Here's the screenshot. If you look at the hotbar, you can see how they should actually look like. This is only with the latest version of light overhaul and electrical age. No other mods.

**Comment by DarkShadow44** [comment]
Mind testing with 2.1.2, once it's approved by curse?
The hand held blocks should work then, the placed blocks probably not.

Interestingly enough, for me the placed blocks are invisible. Is this too the case for you with 2.1.2?

**Comment by Elgh-github** [comment]
I downloaded and installed 2.1.2. After loading up the world from the previous screenshot, handheld items do work. The blocks i placed before, looked the same. I placed some new ones too to test it.

![2019-12-31_09 52 52](https://user-images.githubusercontent.com/40928874/71614484-9a3cb980-2bb4-11ea-90d6-b931e36d51b9.png)

Made a new world, placed some blocks. Some of them are invisible, but it kinda depends on which way I look at them.
![2019-12-31_09 56 15](https://user-images.githubusercontent.com/40928874/71614532-e7b92680-2bb4-11ea-868a-c0784212558b.png)
The only difference between these images is, that it is viewed from a different angle.
![2019-12-31_09 56 32](https://user-images.githubusercontent.com/40928874/71614556-061f2200-2bb5-11ea-9831-591dc1d60861.png)

Also, some of the invisible one's in the middle picture flash in and out of existence, even when i'm not moving. Pretty weird.

**Comment by DarkShadow44** [comment]
Thanks for testing, will take a look at it soon.

**Comment by Elgh-github** [comment]
No problem, happy to help.
Good work on the mod. 👍

**Comment by DarkShadow44** [comment]
Update 2.1.4 is released, could you retest once it's approved on curse? The blocks should now render properly.

**Comment by DarkShadow44** [comment]
FWIW, if you're curious, the problem was that the mod uses immediate rendering. When it tries to set the textures, my shaders don't notice and just draw... something. Solved the issue by rerouting all texture-setting through my mod.

**Comment by Elgh-github** [comment]
Yeah, i'll re-test in the morning. It's really late now where i live.

**Comment by Elgh-github** [comment]
Ok, everything that i had time to test seems to work fine now. Thanks. I'll continue testing after school ends.

**Comment by Elgh-github** [comment]
After further testing, i have yet to find problems. I'll close this issue now. Keep up the good work.
