### ISSUE TITLE
Option to Disable Nether Glowstone

### ISSUE THREAD

**Issue by DarianLStephens** [DarkShadow44/CptsModdingLight#41]
A friend of mine has become very interested in this mod, but isn't a fan of the 'Disco Nether', as he calls it.
I would love to see him give it a go, but claims that is a dealbreaker.

Having a config option to simply disable it would solve this issue.

**Comment by DarkShadow44** [comment]
1.7.10 version is out of date, the rework is written from scratch, so I close this bug.
