### ISSUE TITLE
Incompatible with iChunUtil

### ISSUE THREAD

**Issue by DarianLStephens** [DarkShadow44/CptsModdingLight#42]
Tested with just iChunUtil and Light Overhaul, any surface (Minus water and ice. Transparent, maybe?) exposed to sunlight will be invisible.
You can see through the ground in to caves, which can be lit by most light sources, but they aren't colored correctly.
![2020-03-22_22 24 41](https://user-images.githubusercontent.com/15375876/77248282-5ecdfa80-6c8c-11ea-85e4-fd203c1e3269.png)

If you dig down to these caves, any area that sunlight spreads to will be invisible, with interesting harsh borders where the smooth lighting would fade in to darkness.
![2020-03-22_22 24 49](https://user-images.githubusercontent.com/15375876/77248285-61c8eb00-6c8c-11ea-88c9-b6bf801e517c.png)

![2020-03-22_22 25 01](https://user-images.githubusercontent.com/15375876/77248274-58d81980-6c8c-11ea-8be7-9b1d5dc29843.png)

Placing Blue Glowstone makes the area around it invisible:
![2020-03-22_22 26 09](https://user-images.githubusercontent.com/15375876/77248260-3c3be180-6c8c-11ea-8c56-73d17020cdd8.png)

Other colors don't have the same issue, but the light they emit isn't colored:
![2020-03-22_22 25 48](https://user-images.githubusercontent.com/15375876/77248319-a2286900-6c8c-11ea-8cd2-cc0036be6a8d.png)
Because I noticed it's hard to tell, here's the same area without the red light, so you can see that it does emit some kind of light:
![2020-03-22_22 30 20](https://user-images.githubusercontent.com/15375876/77248343-d3a13480-6c8c-11ea-89b5-a3e0b5c0d8be.png)

Interestingly, certain colors are brighter, even when lacking their intended coloration:
![2020-03-22_22 31 41](https://user-images.githubusercontent.com/15375876/77248366-f7647a80-6c8c-11ea-86bc-be9c6b339e5d.png)

Something else you might have noticed is that the shading is re-enabled on your hand, which I don't recall being the case.

**Comment by DarkShadow44** [comment]
I'll look into it, although it's not too high on my priority list right now.

**Comment by DarianLStephens** [comment]
Out of curiosity, what _are_ you up to?
The only thing I've seen updating on Github is your Wine branch, but I'm not sure that's your doing based on the activity feed.

**Comment by DarkShadow44** [comment]
Mostly busy with RealLife, my day job and the finals for my apprenticeship. After 8 hours programming a day, I rarely find the motivation to work on my hobby projects. Although I plan to continue my projects when I have more free time.
Yes I'm updating the Wine branch from time to time, but that's a 1:1 copy of the upstream Wine.

**Comment by DarkShadow44** [comment]
1.7.10 version is out of date, the rework is written from scratch, so I close this bug.
