### ISSUE TITLE
Display light level in f3 as hex again

### ISSUE THREAD

**Issue by muzikbike** [DarkShadow44/CptsModdingLight#43]
Currently it's just displayed as a decimal number which doesn't say much as to which channels are active.

![2020-07-11_08 27 13](https://user-images.githubusercontent.com/52297970/87219148-cfd71200-c350-11ea-9813-368107524caf.png)

**Comment by DarkShadow44** [comment]
1.7.10 version is out of date, the rework is written from scratch, so I close this bug. Won't affect new version the same way.
