### ISSUE TITLE
Bright pink and orange glowstone are white at the center

### ISSUE THREAD

**Issue by muzikbike** [DarkShadow44/CptsModdingLight#44]
![2020-07-11_08 53 48](https://user-images.githubusercontent.com/52297970/87219588-7244c480-c354-11ea-8c32-1584cc61ec46.png)

Not sure if this duplicates #15

**Comment by DarkShadow44** [comment]
1.7.10 version is out of date, the rework is written from scratch, so I close this bug. Bright light will be dropped.
