### ISSUE TITLE
Bright glowstone contains a dark internal ring

### ISSUE THREAD

**Issue by muzikbike** [DarkShadow44/CptsModdingLight#45]
Not sure if this duplicates #15 or not

![2020-07-11_08 57 56](https://user-images.githubusercontent.com/52297970/87219626-b2a44280-c354-11ea-82ca-7ede68964246.png)

**Comment by DarkShadow44** [comment]
1.7.10 version is out of date, the rework is written from scratch, so I close this bug. Bright light will be dropped.
