### ISSUE TITLE
Maybe split off glowstone variants into a separate mod

### ISSUE THREAD

**Issue by muzikbike** [DarkShadow44/CptsModdingLight#47]
The base mod would have all of the colored lighting code, modified emission by vanilla blocks and the stained glass filtering.

Not sure if this splitting would be neccessary though, especially since the blocks are probably handy for debugging.

**Comment by DarkShadow44** [comment]
1.7.10 version is out of date, the rework is written from scratch, so I close this bug. New mod won't have colored glowstone, just the lighting logic.

**Comment by DarianLStephens** [comment]
I hope the config system will be in this rewrite. I'm still quite looking forward to being able to have mod compatibility without making an actual mod to use the API.
