### ISSUE TITLE
Heat block and heat mechanics

### ISSUE THREAD

**Issue by muzikbike** [DarkShadow44/CptsModdingLight#48]
Like that one Education Edition block, and a similar idea to #1 - the block wouldn't emit any visible light (but would still be measurable through F3?), and wouldn't have any effect on mob spawning, but would contribute to snow and ice accumulation and melting.

Also, since this mod allows for stained glass to filter light, how about a similar thing for heat? Real life glass is opaque to infrared, so covering up a usual light source with glass would still allow all light to pass but stop any undesired melting of blocks.

**Comment by DarkShadow44** [comment]
I doubt this is doable. Currently, "heat" is tied to the light level. For separation I'd need even more space to store the light, and I'm already at the limit.

**Comment by muzikbike** [comment]
Could its functionality be merged into the blacklight block then?

**Comment by DarkShadow44** [comment]
Well, kind of - blocking light will also block "heat".
