### ISSUE TITLE
Colored glowstone tends to break when pushed by pistons from More Pistons Mod

### ISSUE THREAD

**Issue by muzikbike** [DarkShadow44/CptsModdingLight#49]
Vanilla piston functionality seems pretty much perfect, aside from the vanilla issues:
![2020-07-12_07 52 28](https://user-images.githubusercontent.com/52297970/87240845-14c47c80-c415-11ea-9311-bb1b11df2fea.png)
![2020-07-12_07 52 30](https://user-images.githubusercontent.com/52297970/87240847-155d1300-c415-11ea-9e7d-49a151d7fd59.png)

However when pushed by any of the longer pistons from the mod, glowstone tends to just quit emitting light:
![2020-07-12_07 52 52](https://user-images.githubusercontent.com/52297970/87240850-2574f280-c415-11ea-9644-573a721033e7.png)
![2020-07-12_07 52 54](https://user-images.githubusercontent.com/52297970/87240851-26a61f80-c415-11ea-89c9-e17d834ba77d.png)

NK 8 doesn't do particularly well either:
![2020-07-12_07 53 54](https://user-images.githubusercontent.com/52297970/87240859-31f94b00-c415-11ea-9cd0-7257c966e9be.png)
![2020-07-12_07 53 56](https://user-images.githubusercontent.com/52297970/87240860-332a7800-c415-11ea-937e-3002bfd088e8.png)

First found this on the original version of the mod

**Comment by DarkShadow44** [comment]
Not sure why that is. Might look into it some time, but first come other issues.

**Comment by DarkShadow44** [comment]
1.7.10 version is out of date, the rework is written from scratch, so I close this bug.
