### ISSUE TITLE
Block light appears darker than surrounding skylight

### ISSUE THREAD

**Issue by muzikbike** [DarkShadow44/CptsModdingLight#50]
Looks pretty odd, probably a bug
![2020-07-11_09 35 30](https://user-images.githubusercontent.com/52297970/87240984-6f120d00-c416-11ea-80ae-3ea9dbbb6861.png)
![2020-07-12_08 02 27](https://user-images.githubusercontent.com/52297970/87240985-6faaa380-c416-11ea-8114-20108c7e330c.png)
![2020-07-12_08 02 35](https://user-images.githubusercontent.com/52297970/87240987-70dbd080-c416-11ea-856d-1f2182a66821.png)

**Comment by DarianLStephens** [comment]
World lighting was recently reworked to allow you to see light in sunlight.
It may not be the final form, but this general idea is at least intentional.

**Comment by DarkShadow44** [comment]
Well, block light should not darken the surroundings in any case. It's just, that it's not too easy and I didn't figure it out yet...

**Comment by DarkShadow44** [comment]
1.7.10 version is out of date, the rework is written from scratch, so I close this bug.
