### ISSUE TITLE
Fix several vanilla lighting rendering issues

### ISSUE THREAD

**Issue by muzikbike** [DarkShadow44/CptsModdingLight#51]
basically just port sodium's 1.16 lighting fixes backwards. (although I can't really seem to find many of the game's newer lighting bugs currently, probably because of #28)

- Ambient occlusion is inherently directional
![2020-08-08_11 11 39](https://user-images.githubusercontent.com/52297970/89707745-e8931180-d968-11ea-93bb-98b5cbe5ab91.png)

- Smooth lighting underwater is blocky
![2020-08-08_11 13 03](https://user-images.githubusercontent.com/52297970/89707750-f052b600-d968-11ea-89d9-117d9d3a03ce.png)

- This new, related blockiness exclusive to the mod
![2020-08-08_11 20 47](https://user-images.githubusercontent.com/52297970/89707781-445d9a80-d969-11ea-82cb-5cc6e8fb32b9.png)

- Smooth lighting does not work on water's surface
![2020-08-08_11 13 15](https://user-images.githubusercontent.com/52297970/89707756-f8125a80-d968-11ea-9e1e-c6e7a5269d70.png)

**Comment by DarkShadow44** [comment]
1.7.10 version is out of date, the rework is written from scratch, so I close this bug. New version will be compatible with sodium. ;)
